/**
 * The three vocabulary tiers behind every slot.
 *
 * Tier 0 is plausible: it could appear in a peerage guide. Tier 1 is
 * over-egged but defensible. Tier 2 is mundane objects handled with full
 * bureaucratic gravity. The joke never lives in the grammar, only in the
 * contents, so entries must drop into the same sentence frames as their
 * tier 0 cousins.
 *
 * House rules for entries, enforced by test/lexicon.test.ts: no words
 * from MUNDANE may appear in a tier 0 or tier 1 string (the absurdity
 * measure depends on it), no gendered rank words may appear in a shared
 * slot, no reigning house may appear anywhere, and post-nominals must
 * stay unique.
 */

/* ------------------------------------------------------------------ */
/* Territory                                                           */
/* ------------------------------------------------------------------ */

export type StemFlavor =
  | "english" | "german" | "french" | "greek" | "iberian" | "italian" | "turkish";

/** Invented, plausible place stems by linguistic flavor. */
export const STEMS: Record<StemFlavor, readonly string[]> = {
  english: [
    "Wexcombe", "Ashworth", "Calderwick", "Ravensmere", "Brackenholm",
    "Aldbourne", "Farndale", "Greyhurst", "Marlingford", "Thornbury",
    "Osmundwick", "Netherleigh", "Dunsmere", "Harrowfield", "Wychbourne",
    "Wexley", "Ombersleigh", "Cranholt", "Netherbourne", "Marlcombe",
    "Quernmouth", "Withercombe", "Snodbury", "Bexholt", "Fernycroft",
    "Osgarthorpe", "Wamble", "Puddingnorton", "Crowmarsh", "Emberwick",
    "Hollowmere", "Tanglewood Soke", "Wetherfen", "Birchanger", "Doverow",
    "Mickleover Green", "Yarwell Hythe", "Nettlestead", "Ouseburn Parva",
    "Chalkcroft",
  ],
  german: [
    "Wittgenau", "Hohenfelsen", "Sternberg-Adlau", "Eichenwald", "Falkenberg",
    "Lindenau", "Rosenfeld", "Steinbach", "Adlerstein", "Greifenholz",
    "Wolfsheim", "Brandenau", "Kesselburg", "Tannenfels", "Osterfeld",
    "Nebelstein", "Habichtswald", "Dornburg-Krähwinkel", "Silberbach",
    "Eulenberg", "Rabenholz", "Moorlingen", "Kaltenbrunn", "Wespenfeld",
    "Hirschenau", "Nesselwitz", "Grauenstein", "Bibermühl", "Zwischenwasser",
    "Immenrode", "Federheim", "Knollendorf", "Sauerbach", "Wackersleben",
    "Trockenhausen",
  ],
  french: [
    "Montfaucon-le-Bas", "Valcourt", "Bellegarde-sur-Ourse", "Rochefort-l'Abbaye",
    "Chastelnoir", "Fontaine-les-Ormes", "Pierrelune", "Hautmont",
    "Grismont-la-Petite", "Ombreville", "Charnyval", "Brouillac",
    "Aigremont-le-Vieux", "Pont-aux-Grenouilles", "Sombreuil", "Clairefosse",
    "Mirefleur", "Tournebride", "Vaux-les-Deux-Ponts", "Escargotte",
    "Froidchapelle-la-Neuve", "Boisjoli", "Malassis",
  ],
  greek: [
    "Chalkomera", "Argyrokastron-under-the-Walls", "Anthemion", "Petrachora",
    "Kydonopolis", "Melissene", "Chrysokamara", "Porphyra", "Strymnos",
    "Oxydraki", "Kastrofylla", "Nymphodora", "Elaiochori", "Marmarine",
    "Trapezopolis", "Kerkinitis", "Anemomylos", "Stachyopolis", "Krommyda",
    "Pelagonisi", "Chelidonia", "Zygomela", "Thermopigi", "Kalamostrata",
  ],
  iberian: [
    "Vallescuro", "Torrealba", "Villaseca de los Olmos", "Montefrío-la-Vieja",
    "Peñadorada", "Fuenteoscura", "Castrillo de Duero-Menor", "Sierraluz",
    "Valdemimbre", "Torreciega", "Salinas de Arriba", "Peñagrís",
    "Villaverde del Camino Viejo", "Fuentelobos", "Cerroalto", "Lagunilla Seca",
    "Puentecillo de la Niebla", "Montealegre el Chico", "Rocafrida",
    "Zarzalejo de los Vientos", "Almendrilla", "Vadollano", "Cuevasblancas",
  ],
  italian: [
    "Castelvetri", "Pietraforte", "Selvamora", "Montefosco", "Torregrigia",
    "Valdispina", "Rocca d'Ombra", "Poggio Lucente", "Civitella del Vento",
    "Borgomarcio", "Fontanabruna", "Collealtino", "Serrafredda",
    "Pievescura", "Grottalunga", "Campomorto di Sotto", "Lucciolaia",
    "Vignaccia", "Ripabianca del Colle", "Sassoscritto", "Torricella Muta",
    "Bosconero", "Acquachiara", "Poggibonizzo",
  ],
  turkish: [
    "Gümüşkaya", "Taşdere", "Kumluova", "Yıldıztepe", "Akpınar-of-the-Meadows",
    "Karasu Vale", "Gülbahçe", "Demirhisar", "Ayvalıdere", "Kartaltepe",
    "Sazlıgöl", "İncirköy", "Bakıryokuş", "Serçelik", "Narlıbağ",
    "Kavakaltı", "Tuzluburun", "Yelkovan", "Balpınar", "Çamlıyaka",
  ],
};

/**
 * The mundane nouns behind tier 2. Kept in one place because the
 * absurdity of an output is measured by how often these appear, so no
 * word here may ever surface in a tier 0 or tier 1 entry.
 */
export const MUNDANE = [
  "Cupboard", "Pantry", "Larder", "Stairwell", "Biscuit", "Teapot",
  "Spoons", "Thermostat", "Airing-Cupboard", "Ottoman", "Draining Board",
  "Mantelpiece", "Hatstand", "Skirting Board", "Linen Press", "Coal Scuttle",
  "Boot Room", "Vestibule", "Doormat", "Banister", "Umbrella Stand",
  "Windowsill", "Butter Dish", "Egg Cup", "Toast Rack", "Sideboard",
  "Wainscot", "Draught Excluder", "Second-Best Chairs", "Spare Keys",
  "Doilies", "Tea Cosy", "Antimacassar", "Fork", "Towel", "Receipt", "Damp",
  "Bread Bin", "Cake Tin", "Biscuit Barrel", "Butter Knife", "Fish Slice",
  "Gravy Boat", "Salad Spinner", "Egg Timer", "Oven Glove", "Pot Holder",
  "Trivet", "Colander", "Whisk", "Ladle", "Rolling Pin", "Pastry Brush",
  "Cheese Dome", "Cruet", "Mustard Pot", "Jam Spoon", "Sugar Tongs",
  "Napkin Ring", "Placemat", "Coaster", "Table Runner", "Serviette",
  "Tablecloth", "Candle Snuffer", "Radiator", "Boiler", "Immersion Heater",
  "Fuse Box", "Extension Lead", "Doorbell", "Letter Box", "Boot Scraper",
  "Shoe Horn", "Coat Hook", "Peg Rail", "Airing Rack", "Clothes Horse",
  "Peg Basket", "Laundry Basket", "Ironing Board", "Flat Iron", "Mangle",
  "Washboard", "Dustpan", "Carpet Beater", "Feather Duster", "Broom Cupboard",
  "Mop Bucket", "Compost Heap", "Water Butt", "Garden Hose", "Watering Can",
  "Secateurs", "Trowel", "Wheelbarrow", "Greenhouse", "Potting Shed",
  "Bird Table", "Garden Gnome", "Deckchair", "Windbreak", "Picnic Hamper",
  "Thermos", "Sandwich Tin", "Ball of String", "Paperclip", "Stapler",
  "Hole Punch", "Blotter", "Inkwell", "Filing Cabinet", "In-Tray",
  "Out-Tray", "Minute Book", "Agenda", "Quorum", "Sub-Committee",
  "Standing Order", "Bulldog Clip", "Drawing Pin", "Notice Board",
  "Suggestion Box", "Lost Property", "Cloakroom Ticket", "Raffle",
  "Tombola", "Jumble Sale", "Spirit Level", "Radiator Key", "Loft Ladder",
  "Junk Drawer", "Odd Socks", "Spare Buttons", "Good Scissors",
  "Guest Towels", "Good China", "Takeaway Menus", "Instruction Manuals",
  "Warranty Cards", "Rota",
] as const;

export const TERRITORY_PREFIXES = [
  "Upper", "Lower", "Nether", "Greater", "Lesser", "Outer", "Further",
  "Hither", "Old", "New", "Much", "Little", "Great", "Chipping", "Long",
  "Market", "Steeple", "Over", "Middle", "Cold", "Dry",
] as const;

export const TERRITORY_SUFFIXES = [
  "burg", "stein", "heim", "shire", "wick", "mouth", "ington", "bourne",
  "ford", "stadt", "dorf", "au", "bach", "berg", "thorpe", "combe",
  "mere", "hurst", "leigh", "garth", "fell", "grange", "hithe", "low",
  "sett", "worth", "den", "field", "holm", "gate",
] as const;

export const STEM_SYLLABLES = [
  "Alden", "Bram", "Cald", "Dun", "Ester", "Fal", "Grim", "Hessel",
  "Ise", "Kettle", "Lang", "Mar", "Nor", "Oster", "Quern", "Ravens",
  "Sel", "Thorn", "Ulver", "Wex", "Bex", "Cran", "Dray", "Elm", "Fen",
  "Gars", "Hax", "Kel", "Lund", "Mickle", "Nut", "Ock", "Pex", "Quill",
  "Rham", "Snod", "Tred", "Ux", "Wam", "Yar",
] as const;

/* ------------------------------------------------------------------ */
/* Epithets                                                            */
/* ------------------------------------------------------------------ */

export const EPITHETS = {
  t0: [
    "the Bold", "the Great", "the Wise", "the Pious", "the Fair",
    "the Elder", "the Younger", "the Steadfast", "the Just",
    "the Magnificent", "the Silent", "the Good",
    "the Valiant", "the Prudent", "the Serene", "the Learned",
    "the Devout", "the Merciful", "the Stern", "the Golden",
    "the Peaceable", "the Victorious", "the Lawgiver", "the Restorer",
    "the Navigator", "the Chaste", "the Well-Beloved", "the Affable",
    "the Old", "the Young", "the Tall", "the Proud", "the Rich",
    "the Generous", "the Simple", "the Noble", "the Gentle", "the Grim",
    "the Strong", "the Fearless", "the Illustrious", "the Splendid",
    "the Constant", "the Watchful", "the Far-Sighted", "the Deep-Minded",
    "the Even-Handed", "the Open-Handed", "the White", "the Black",
    "the Red", "the Grey", "the Hammer", "the Builder", "the Founder",
    "the Unifier", "the Peacemaker", "the Pilgrim", "the Voyager",
    "the Scholar", "the Falconer", "the Huntsman", "the Gardener",
    "the Bridge-Builder", "the Long-Reigned", "the Beloved",
    "the Thunderbolt", "the Lion-Hearted", "the Oak-Hearted",
    "the Sea-Farer", "the Law-Speaker", "the Well-Counselled",
  ],
  t1: [
    "the Unready", "the Fat", "the Bald", "the Stammerer",
    "the Mostly Reasonable", "the Adequate", "the Late (while living)",
    "the Quarrelsome", "the Posthumous", "the Approximate",
    "the Unavoidable", "the Easily Startled",
    "the Hesitant", "the Litigious", "the Overdue", "the Provisional",
    "the Alleged", "the Presumptive", "the Probable", "the Second-Best",
    "the Unpunctual", "the Interim", "the Acting", "the Substitute",
    "the Penultimate", "the Surplus", "the Optional", "the Intermittent",
    "the Unverified", "the Apocryphal", "the Debatable", "the Rescheduled",
    "the Postponed", "the Abridged", "the Unabridged", "the Revised",
    "the Amended", "the Annotated", "the Indecisive", "the Forgetful",
    "the Nearly Great", "the Almost Wise", "the Briefly Bold",
    "the Formerly Great", "the Reluctant", "the Unconsulted",
    "the Overlooked", "the Underestimated", "the Mildly Feared",
    "the Locally Famous", "the Regionally Renowned",
    "the Frequently Confused", "the Seldom Right", "the Often Elsewhere",
    "the Habitually Late", "the Broadly Tolerated",
    "the Conditionally Beloved", "the Recently Awake", "the Well-Rested",
    "the Comfortable", "the Adequately Prepared", "the Semi-Legendary",
    "the Largely Ceremonial", "the Notionally Fearsome",
    "the Widely Rumoured", "the Under-Documented", "the Nominal",
    "the Averagely Built", "the Fair-to-Middling", "the Passable",
    "the Presentable", "the Roughly Punctual", "the Almost Unanimous",
    "the Twice-Crowned (Once by Accident)", "the Self-Styled",
    "the Occasionally Magnificent", "the Weather-Dependent",
    "the Moderately Terrible", "the Politely Feared",
    "the Technically Correct", "the Provisionally Immortal",
    "the Broadly Accurate", "the Suitably Impressed",
    "the Un-Reconfirmed", "the Vaguely Remembered",
    "the Second of the Same Name (Probably)", "the Plausible",
    "the Well-Meaning", "the Once-Removed", "the Understated",
    "the Lightly Armoured", "the Sometimes Great",
  ],
  t2: [
    "the Insufficiently Boiled", "the Fully Reimbursed",
    "the Fourth of That Name", "the Slightly Damp", "the Punctual",
    "the Twice-Postponed", "the Beige", "the Lightly Salted",
    "the Regrettably Informed", "the Structurally Sound",
    "the Correctly Filed", "the Room-Temperature",
    "the Laminated", "the Pre-Approved", "the Fully Depreciated",
    "the Tax-Deductible", "the Non-Refundable", "the Correctly Stapled",
    "the Double-Spaced", "the Alphabetized", "the Cross-Referenced",
    "the Filed Under Miscellaneous", "the Misfiled", "the Photocopied",
    "the Carbon-Copied", "the Duly Noted", "the Minuted", "the Tabled",
    "the Adjourned", "the Quorate", "the Seconded",
    "the Carried Unanimously", "the Ratified", "the Initialled",
    "the Countersigned", "the Embossed", "the Watermarked",
    "the Recyclable", "the Dishwasher-Safe", "the Microwaveable",
    "the Ovenproof", "the Non-Stick", "the Wipe-Clean",
    "the Machine-Washable", "the Drip-Dry", "the Crease-Resistant",
    "the Pre-Shrunk", "the Flame-Retardant", "the Partially Assembled",
    "the Flat-Packed", "the Batch-Cooked", "the Lightly Buttered",
    "the Well-Seasoned", "the Overwatered", "the Underwatered",
    "the Freshly Grated", "the Twice-Baked", "the Al Dente",
    "the Decaffeinated", "the Semi-Skimmed", "the Pasteurized",
    "the Free-Range", "the Locally Sourced", "the Gently Simmered",
    "the Strained Twice", "the Well-Whisked", "the Recently Dusted",
    "the Load-Bearing", "the Damp-Proofed", "the Double-Glazed",
    "the Draught-Proofed", "the Newly Grouted", "the Regrouted",
    "the Repainted (Magnolia)", "the Magnolia", "the Taupe",
    "the Eggshell", "the Matte", "the Semi-Gloss", "the Wipeable",
    "the Hypoallergenic", "the Biodegradable", "the Shatterproof",
    "the Tumble-Dried", "the Line-Dried", "the Colour-Fast",
    "the Stain-Resistant", "the Weatherproofed",
    "the Self-Raising", "the Sell-By-Dated", "the Vacuum-Packed",
    "the Resealable", "the Portion-Controlled", "the Fun-Sized",
    "the Long-Life", "the Concentrated (Dilute to Taste)",
    "the Suitable for Vegetarians", "the Mild-to-Medium",
    "the Assembled Without Instructions", "the Shrink-Wrapped",
    "the Pre-Soaked", "the Best Served Chilled",
    "the Lightly Ironed", "the Provisionally Dusted",
    "the Bleachable", "the Gluten-Free",
    "the Fitted", "the Under Warranty",
    "the Out of Warranty", "the Awaiting Collection",
    "the Signed For on Delivery", "the Left With a Neighbour",
    "the Returned to Sender", "the Second-Class Post",
    "the Franked", "the Redirected", "the Held at the Sorting Office",
    "the Certified Damp-Free (1974)", "the Grade II Listed",
    "the Pending Planning Permission", "the Structurally Cautioned",
    "the Fully Ventilated", "the Lagged", "the Insulated to Standard",
    "the Serviced Annually", "the Due a Service",
  ],
} as const;

/**
 * "The Fourth of That Name" only lands when the ordinal is II, so the
 * generator treats this entry as conditional.
 */
export const CONTRADICTORY_EPITHET = "the Fourth of That Name";

/* ------------------------------------------------------------------ */
/* Offices                                                             */
/* ------------------------------------------------------------------ */

export interface OfficeRow {
  name: string;
  hereditary: boolean;
  to?: string;
}

export const OFFICES: { t0: readonly OfficeRow[]; t1: readonly OfficeRow[]; t2: readonly OfficeRow[] } = {
  // Real historical offices, defunct, generic, or gloriously parochial.
  // The village ones (Ale-Conner, Pinder, Hayward) are genuine.
  t0: [
    { name: "Master of the Horse", hereditary: false },
    { name: "Lord High Admiral", hereditary: false },
    { name: "Keeper of the Privy Seal", hereditary: false },
    { name: "Warden of the Marches", hereditary: false },
    { name: "Lord Warden of the Cinque Ports", hereditary: false },
    { name: "Grand Falconer", hereditary: true },
    { name: "Custos Rotulorum", hereditary: false },
    { name: "Chief Butler", hereditary: true },
    { name: "Lord High Steward", hereditary: false },
    { name: "Master of the Buckhounds", hereditary: false },
    { name: "Clerk of the Green Cloth", hereditary: false },
    { name: "Master of the Revels", hereditary: false },
    { name: "Keeper of the Great Seal", hereditary: false },
    { name: "Lord High Constable", hereditary: false },
    { name: "Master of the Great Wardrobe", hereditary: false },
    { name: "Clerk of the Closet", hereditary: false },
    { name: "Yeoman of the Cellar", hereditary: false },
    { name: "Master of the Jewel Office", hereditary: false },
    { name: "Marshal of the Array", hereditary: false },
    { name: "Warden of the Mint", hereditary: false },
    { name: "Searcher of the Sanctuary", hereditary: false },
    { name: "Herb Strewer", hereditary: true },
    { name: "Master of the Otterhounds", hereditary: false },
    { name: "Verderer of the Forest", hereditary: false },
    { name: "Portreeve", hereditary: false },
    { name: "Ale-Conner", hereditary: false },
    { name: "Beadle", hereditary: false },
    { name: "Hayward", hereditary: false },
    { name: "Pinder", hereditary: false },
    { name: "Common Crier", hereditary: false },
    { name: "Warden of the Assize of Bread", hereditary: false },
    { name: "Arch-Chancellor", hereditary: true, to: "the Empire" },
    { name: "Arch-Marshal", hereditary: true, to: "the Empire" },
    { name: "Arch-Chamberlain", hereditary: true, to: "the Empire" },
    { name: "Arch-Cupbearer", hereditary: true, to: "the Empire" },
    { name: "Arch-Steward", hereditary: true, to: "the Empire" },
    { name: "Arch-Bannerbearer", hereditary: true, to: "the Empire" },
    { name: "Arch-Huntsman", hereditary: true, to: "the Empire" },
    { name: "Defterdar", hereditary: false },
    { name: "Nişancı", hereditary: false },
    { name: "Bostancıbaşı", hereditary: false },
    { name: "Alférez Mayor", hereditary: true },
    { name: "Gonfaloniere of Justice", hereditary: false },
    { name: "Keeper of the Rolls of the March", hereditary: false },
    { name: "Steward of the Honour Court", hereditary: false },
    { name: "Bailiff of the Franchises", hereditary: false },
    { name: "Receiver-General", hereditary: false },
    { name: "Master of the Posts", hereditary: false },
    { name: "Surveyor of the Walls", hereditary: false },
    { name: "Keeper of the Standard Measures", hereditary: false },
  ],
  t1: [
    { name: "Cup-Bearer", hereditary: true, to: "the Electoral Court" },
    { name: "Warden of the Lesser Forests", hereditary: false },
    { name: "Grand Master of the Hunt (Suspended)", hereditary: false },
    { name: "Keeper of the Second Seal", hereditary: false },
    { name: "Under-Falconer", hereditary: false, to: "the Margravial Mews" },
    { name: "Comptroller of the Outer Marches", hereditary: false },
    { name: "Surveyor of the Upper and Nether Roads", hereditary: false },
    { name: "Standard-Bearer", hereditary: true, to: "the Court of the Two Wexcombes" },
    { name: "Keeper of the Winter Bridges", hereditary: false },
    { name: "Warden of the Bee Skeps", hereditary: true },
    { name: "Surveyor of the Dykes and Sluices", hereditary: false },
    { name: "Bailiff of the Upper Fords", hereditary: false },
    { name: "Keeper of the Beacon Chain", hereditary: false },
    { name: "Warden of the Salt Roads", hereditary: false },
    { name: "Master of the Ferry (Disputed Bank)", hereditary: false },
    { name: "Comptroller of the Bridge Tolls", hereditary: false },
    { name: "Keeper of the Tide Tables", hereditary: false },
    { name: "Warden of the Eel Weirs", hereditary: true },
    { name: "Clerk of the Beacons", hereditary: false },
    { name: "Under-Steward of the Home Farm", hereditary: false },
    { name: "Keeper of the Second Falcon", hereditary: false },
    { name: "Master of the Winter Hunt", hereditary: false },
    { name: "Warden of the Orchard Walls", hereditary: false },
    { name: "Keeper of the Bell Ropes", hereditary: false },
    { name: "Surveyor of the Chimneys", hereditary: false },
    { name: "Clerk of the Wells", hereditary: false },
    { name: "Master of the Dovecotes", hereditary: true },
    { name: "Keeper of the Boundary Stones", hereditary: false },
    { name: "Warden of the Mill Race", hereditary: false },
    { name: "Gatekeeper of the Postern (Winter Only)", hereditary: false },
    { name: "Keeper of the Hourglasses", hereditary: false },
    { name: "Warden of the Goose Common", hereditary: false },
    { name: "Master of the Pigeon Post", hereditary: false },
    { name: "Under-Warden of the Lesser Gate", hereditary: false },
    { name: "Keeper of the Old Maps (Annotated)", hereditary: false },
    { name: "Surveyor of the Middle Distance", hereditary: false },
    { name: "Clerk of the Weather (Observations Only)", hereditary: false },
    { name: "Warden of the Second Bridge", hereditary: false },
    { name: "Keeper of the Ceremonial Ladder", hereditary: true },
    { name: "Master of the Left Stirrup", hereditary: true },
    { name: "Comptroller of the Candle Ends", hereditary: false },
    { name: "Keeper of the Visitors' Book", hereditary: false },
    { name: "Warden of the Echo", hereditary: false },
    { name: "Under-Herald of the Eastern Approaches", hereditary: false },
    { name: "Keeper of the Processional Route (Wet Alternative)", hereditary: false },
    { name: "Master of the Moat (Ornamental)", hereditary: false },
    { name: "Clerk of the Sundial", hereditary: false },
    { name: "Warden of the Deer Leap", hereditary: false },
    { name: "Keeper of the Falcon Hoods", hereditary: false },
    { name: "Surveyor of the Battlements (Decorative)", hereditary: false },
    { name: "Bearer of the Lesser Mace", hereditary: true },
    { name: "Keeper of the Foundation Stone", hereditary: false },
    { name: "Warden of the Ha-Ha", hereditary: false },
    { name: "Master of the Topiary", hereditary: false },
    { name: "Keeper of the Ceremonial Umbrella", hereditary: true },
    { name: "Clerk of the Precedence Rolls", hereditary: false },
    { name: "Warden of the Long Gallery", hereditary: false },
    { name: "Keeper of the Spare Crown (Travel)", hereditary: false },
  ],
  t2: [
    { name: "Keeper of the Spoons", hereditary: true },
    { name: "Warden of the Lesser Stairwell", hereditary: false },
    { name: "Lord High Adjuster of the Thermostat", hereditary: false },
    { name: "Grand Falconer", hereditary: true, to: "the Pantry" },
    { name: "Custodian of the Second-Best Chairs", hereditary: false },
    { name: "Comptroller of the Biscuit", hereditary: false },
    { name: "Master of the Draining Board", hereditary: false },
    { name: "Keeper of the Draught Excluder", hereditary: true },
    { name: "Warden of the Decorative Soaps", hereditary: false },
    { name: "Lord High Rearranger of the Hall Cupboard", hereditary: false },
    { name: "Clerk of the Doilies", hereditary: false },
    { name: "Surveyor of the Queue", hereditary: false },
    { name: "Remembrancer of the Spare Keys", hereditary: true },
    { name: "Keeper of the Bread Bin", hereditary: true },
    { name: "Lord High Straightener of the Rugs", hereditary: false },
    { name: "Warden of the Good Scissors", hereditary: true },
    { name: "Custodian of the Remote Control", hereditary: false },
    { name: "Keeper of the Spare Batteries (Assorted Sizes)", hereditary: false },
    { name: "Master of the Junk Drawer", hereditary: true },
    { name: "Comptroller of the Plastic Tubs (Lids Various)", hereditary: false },
    { name: "Warden of the Odd Socks", hereditary: false },
    { name: "Lord High Untangler of the Cables", hereditary: false },
    { name: "Keeper of the Takeaway Menus", hereditary: false },
    { name: "Clerk of the Shopping List", hereditary: false },
    { name: "Remembrancer of the Bins (Collection Days)", hereditary: false },
    { name: "Master of the Loft Ladder", hereditary: false },
    { name: "Keeper of the Seasonal Decorations (Attic)", hereditary: false },
    { name: "Warden of the Guest Towels", hereditary: false },
    { name: "Custodian of the Good China", hereditary: true },
    { name: "Keeper of the Receipts (Shoebox)", hereditary: false },
    { name: "Surveyor of the Damp (Rising)", hereditary: false },
    { name: "Comptroller of the Draughts", hereditary: false },
    { name: "Warden of the Creaky Stair (Third)", hereditary: false },
    { name: "Lord High Winder of the Clocks", hereditary: false },
    { name: "Keeper of the Instruction Manuals", hereditary: false },
    { name: "Master of the Allen Keys", hereditary: false },
    { name: "Clerk of the Warranty Cards", hereditary: false },
    { name: "Keeper of the Spare Buttons (Assorted)", hereditary: true },
    { name: "Warden of the Biscuit Tin (Night)", hereditary: false },
    { name: "Groom of the Umbrella Stand", hereditary: false },
    { name: "Yeoman of the Cutlery Drawer", hereditary: false },
    { name: "Herald of the Kettle", hereditary: false },
    { name: "Marshal of the Queue (Post Office)", hereditary: false },
    { name: "Keeper of the Doormat (Welcome Withdrawn)", hereditary: false },
    { name: "Custodian of the Spirit Level", hereditary: false },
    { name: "Keeper of the Radiator Key", hereditary: true },
    { name: "Warden of the Fuse Box", hereditary: false },
    { name: "Master of the Extension Lead (Fully Unwound)", hereditary: false },
    { name: "Clerk of the Notice Board", hereditary: false },
    { name: "Keeper of the Suggestion Box (Locked)", hereditary: false },
    { name: "Registrar of the Lost Property", hereditary: false },
    { name: "Comptroller of the Cloakroom Tickets", hereditary: false },
    { name: "Master of the Raffle", hereditary: false },
    { name: "Adjudicator of the Tombola", hereditary: false },
    { name: "Warden of the Jumble Sale (Mornings)", hereditary: false },
    { name: "Keeper of the Minute Book", hereditary: false },
    { name: "Guardian of the Agenda (Any Other Business)", hereditary: false },
    { name: "Teller of the Show of Hands", hereditary: false },
    { name: "Keeper of the Gravy Boat", hereditary: true },
    { name: "Warden of the Salad Spinner", hereditary: false },
    { name: "Master of the Egg Timer", hereditary: false },
    { name: "Bearer of the Oven Gloves", hereditary: true },
    { name: "Keeper of the Trivet", hereditary: false },
    { name: "Lord High Wielder of the Whisk", hereditary: false },
    { name: "Custodian of the Rolling Pin", hereditary: true },
    { name: "Keeper of the Cheese Dome", hereditary: false },
    { name: "Warden of the Cruet", hereditary: false },
    { name: "Master of the Mustard Pot", hereditary: false },
    { name: "Keeper of the Napkin Rings (Sunday Set)", hereditary: false },
    { name: "Layer of the Placemats", hereditary: false },
    { name: "Warden of the Table Runner", hereditary: false },
    { name: "Snuffer of the Candles (By Appointment)", hereditary: false },
    { name: "Stoker of the Boiler (Mornings)", hereditary: false },
    { name: "Keeper of the Immersion Heater Switch", hereditary: false },
    { name: "Warden of the Letter Box (Inward)", hereditary: false },
    { name: "Keeper of the Coat Hooks (Allocated)", hereditary: false },
    { name: "Master of the Clothes Horse", hereditary: false },
    { name: "Warden of the Laundry Basket (Lights)", hereditary: false },
    { name: "Warden of the Laundry Basket (Darks)", hereditary: false },
    { name: "Presser of the Flat Iron", hereditary: false },
    { name: "Keeper of the Dustpan and Its Brush", hereditary: true },
    { name: "Wielder of the Feather Duster (State Occasions)", hereditary: false },
    { name: "Keeper of the Broom Cupboard", hereditary: true },
    { name: "Warden of the Mop Bucket", hereditary: false },
    { name: "Turner of the Compost Heap", hereditary: false },
    { name: "Keeper of the Water Butt", hereditary: false },
    { name: "Uncoiler of the Garden Hose", hereditary: false },
    { name: "Bearer of the Watering Can (Even Days)", hereditary: false },
    { name: "Keeper of the Secateurs", hereditary: true },
    { name: "Master of the Wheelbarrow", hereditary: false },
    { name: "Warden of the Greenhouse (Ventilation)", hereditary: false },
    { name: "Keeper of the Potting Shed Key", hereditary: true },
    { name: "Provisioner of the Bird Table", hereditary: false },
    { name: "Guardian of the Garden Gnome", hereditary: false },
    { name: "Unfolder of the Deckchairs", hereditary: false },
    { name: "Keeper of the Picnic Hamper (Inventory Attached)", hereditary: false },
    { name: "Filler of the Thermos", hereditary: false },
    { name: "Keeper of the Ball of String (Too Short to Save)", hereditary: false },
    { name: "Comptroller of the Paperclips", hereditary: false },
    { name: "Master of the Stapler (Refills Pending)", hereditary: false },
    { name: "Keeper of the Hole Punch", hereditary: false },
    { name: "Warden of the In-Tray", hereditary: false },
    { name: "Warden of the Out-Tray", hereditary: false },
    { name: "Keeper of the Filing Cabinet (Bottom Drawer Sticks)", hereditary: false },
  ],
};

/* ------------------------------------------------------------------ */
/* Orders and other honours                                            */
/* ------------------------------------------------------------------ */

export interface OrderRow {
  /** "the Silver Heron" reads as "the Order of the Silver Heron". */
  name: string;
  /** Post-nominal initials appended to the grade letter: "SH" makes KSH. */
  initials: string;
  /**
   * Single-class orders (as the Garter is) carry fixed conventional
   * post-nominals instead of graded ones.
   */
  single?: { m: string; f: string; n: string };
  /** Tier 2 grades sometimes carry an augmentation. */
  augment?: readonly string[];
}

export const ORDERS: { t0: readonly OrderRow[]; t1: readonly OrderRow[]; t2: readonly OrderRow[] } = {
  // Historical orders, post-nominals per convention. The Broom-Flower
  // (Cosse de Genêt) and the Porcupine were real French orders; the
  // Dragon was Sigismund's, the Swan Brandenburg's, all long defunct.
  t0: [
    { name: "the Garter", initials: "G", single: { m: "KG", f: "LG", n: "KG" } },
    { name: "the Golden Fleece", initials: "GF", single: { m: "GF", f: "GF", n: "GF" } },
    { name: "the Elephant", initials: "E", single: { m: "RE", f: "RE", n: "RE" } },
    { name: "St. Hubert", initials: "SHu", single: { m: "KStH", f: "DStH", n: "KStH" } },
    { name: "the Iron Crown", initials: "IC" },
    { name: "the Crescent", initials: "C", single: { m: "KC", f: "KC", n: "KC" } },
    { name: "the Amaranth", initials: "A", single: { m: "KA", f: "LA", n: "KA" } },
    { name: "the Dragon", initials: "Dr", single: { m: "KDr", f: "DDr", n: "KDr" } },
    { name: "the Sword", initials: "Sw", single: { m: "KSd", f: "KSd", n: "KSd" } },
    { name: "the Star", initials: "St", single: { m: "KSt", f: "KSt", n: "KSt" } },
    { name: "the Ship", initials: "Sp", single: { m: "KSp", f: "KSp", n: "KSp" } },
    { name: "the Ermine", initials: "Er", single: { m: "KE", f: "KE", n: "KE" } },
    { name: "the Swan", initials: "Sn", single: { m: "KSw", f: "KSw", n: "KSw" } },
    { name: "the Broom-Flower", initials: "BFl", single: { m: "CG", f: "CG", n: "CG" } },
    { name: "the Porcupine", initials: "P", single: { m: "KP", f: "KP", n: "KP" } },
  ],
  t1: [
    { name: "the Silver Heron", initials: "SH" },
    { name: "the Wittgenau Lion", initials: "WL" },
    { name: "Merit of the Two Wexcombes", initials: "MW" },
    { name: "the Oaken Garland", initials: "OG" },
    { name: "the Falcon of Hohenfelsen", initials: "FH" },
    { name: "the Starry Girdle", initials: "SG" },
    { name: "the Vigilant Owl", initials: "VO" },
    { name: "the Azure Pelican", initials: "AP" },
    { name: "the Golden Marten", initials: "GM" },
    { name: "the White Hart", initials: "WH" },
    { name: "the Crowned Salmon", initials: "CS" },
    { name: "the Radiant Spur", initials: "RS" },
    { name: "the Green Oak", initials: "GK" },
    { name: "the Twin Castles", initials: "CC" },
    { name: "the Watchful Crane", initials: "WC" },
    { name: "the Ivory Horn", initials: "IH" },
    { name: "the Amber Rose", initials: "AR" },
    { name: "the Iron Gate", initials: "IG" },
    { name: "the Three Fountains", initials: "TF" },
    { name: "the Silver Bough", initials: "SB" },
    { name: "the Burning Lamp", initials: "BL" },
    { name: "the Faithful Hound", initials: "HD" },
    { name: "the Northern Lily", initials: "NL" },
    { name: "the Golden Quill", initials: "GQ" },
    { name: "the Crimson Tower", initials: "CT" },
    { name: "the Leaping Trout", initials: "LT" },
    { name: "the Oaken Shield", initials: "OS" },
    { name: "the Winter Sun", initials: "WS" },
    { name: "the Bridge and Beacon", initials: "BB" },
    { name: "the Marble Column", initials: "MC" },
    { name: "the Bright Meadow", initials: "BM" },
    { name: "the Anchored Star", initials: "AS" },
    { name: "Merit of Osterfeld", initials: "MO" },
  ],
  t2: [
    {
      name: "the Slightly Bent Fork", initials: "BF",
      augment: ["with Collar and Receipt", "with Crossed Spoons"],
    },
    { name: "the Towel", initials: "TW", augment: ["with Fringe"] },
    { name: "the Damp", initials: "D", augment: ["with Collar and Receipt"] },
    { name: "the Second Drawer", initials: "SD" },
    { name: "the Overwound Clock", initials: "OC" },
    { name: "the Tea Cosy", initials: "TC", augment: ["with Pom-Pom"] },
    { name: "Merit of the Pantry", initials: "MP" },
    { name: "the Bread Bin", initials: "BN", augment: ["with Crumb Tray"] },
    { name: "the Sugar Tongs", initials: "ST", augment: ["with Second Prong"] },
    { name: "the Gravy Boat", initials: "GB", augment: ["with Matching Saucer"] },
    { name: "the Salad Spinner", initials: "SS" },
    { name: "the Egg Timer", initials: "ET", augment: ["with Most of the Sand"] },
    { name: "the Oven Glove", initials: "OV", augment: ["with Reinforced Thumb"] },
    { name: "the Immersion Heater", initials: "IM" },
    { name: "the Extension Lead", initials: "EL", augment: ["with Spare Fuse"] },
    { name: "the Filing Cabinet", initials: "FC", augment: ["with Both Keys"] },
    { name: "the Bulldog Clip", initials: "BC" },
    { name: "the Drawing Pin", initials: "DP", augment: ["with Original Packaging"] },
    { name: "the Suggestion Box", initials: "SX", augment: ["with Pencil (Attached by String)"] },
    { name: "the Lost Property", initials: "LP" },
    { name: "the Cloakroom Ticket", initials: "CK" },
    { name: "the Raffle", initials: "RF", augment: ["with Book of Stubs"] },
    { name: "the Watering Can", initials: "WN", augment: ["with Rose Attachment"] },
    { name: "the Compost Heap", initials: "CH" },
    { name: "the Wheelbarrow", initials: "WB", augment: ["with Inflated Tyre"] },
    { name: "the Potting Shed", initials: "PS" },
    { name: "the Bird Table", initials: "BT" },
    { name: "the Deckchair", initials: "DC", augment: ["with Instructions (Lost)"] },
    { name: "the Picnic Hamper", initials: "PH", augment: ["with Inventory"] },
    { name: "the Thermos", initials: "TH", augment: ["with Original Cup"] },
    { name: "the Ironing Board", initials: "IB", augment: ["in Avocado"] },
    { name: "the Clothes Horse", initials: "CL" },
    { name: "the Feather Duster", initials: "FE" },
    { name: "the Dustpan", initials: "DU", augment: ["with Its Brush"] },
    { name: "the Mangle", initials: "MG" },
    { name: "the Flat Iron", initials: "FI" },
    { name: "the Spare Buttons", initials: "SU", augment: ["Assorted"] },
    { name: "the Odd Socks", initials: "OD", augment: ["with Provisional Pairing"] },
    { name: "the Junk Drawer", initials: "JD" },
    { name: "the Good Scissors", initials: "GS", augment: ["with Usage Rights (Revocable)"] },
    { name: "the Loft Ladder", initials: "LL" },
    { name: "the Fuse Box", initials: "FB", augment: ["with Torch (Nearby)"] },
    { name: "the Notice Board", initials: "NB", augment: ["with Four Matching Pins"] },
    { name: "the Bin Rota", initials: "BR" },
    { name: "the Guest Towels", initials: "GT", augment: ["Display Only"] },
    { name: "the Good China", initials: "GC", augment: ["with Full Service for Six"] },
    { name: "the Spirit Level", initials: "SL", augment: ["with Bubble Centred"] },
    { name: "the Radiator Key", initials: "RK" },
    { name: "the Carriage Clock", initials: "CA", augment: ["Presented on Retirement"] },
    { name: "the Reserved Parking", initials: "RP" },
    { name: "the Long Minute", initials: "LMn" },
    { name: "the Second Sitting", initials: "SC" },
    { name: "the Hall Table", initials: "HT", augment: ["with Bowl for Keys"] },
  ],
};

/** Grade prefixes for graded orders, most senior first. */
export const GRADES: readonly {
  letter: string;
  words: { m: string; f: string; n: string };
}[] = [
  { letter: "G", words: { m: "Knight Grand Cross", f: "Dame Grand Cross", n: "Grand Cross" } },
  { letter: "K", words: { m: "Knight Commander", f: "Dame Commander", n: "Commander" } },
  { letter: "C", words: { m: "Companion", f: "Companion", n: "Companion" } },
  { letter: "M", words: { m: "Member", f: "Member", n: "Member" } },
];

export interface DecorationRow {
  name: string;
  postNominal: string;
}

export const DECORATIONS: { t0: readonly DecorationRow[]; t1: readonly DecorationRow[]; t2: readonly DecorationRow[] } = {
  t0: [
    { name: "the Cross of Merit", postNominal: "CM" },
    { name: "the Medal of Valour", postNominal: "MV" },
    { name: "the Cross of Valour", postNominal: "CV" },
    { name: "the Star of Merit", postNominal: "SM" },
    { name: "the Long Service Cross", postNominal: "LSC" },
    { name: "the Medal for Zeal", postNominal: "MZ" },
    { name: "the Frontier Medal", postNominal: "FM" },
    { name: "the Flood Service Medal", postNominal: "FSM" },
    { name: "the Coronation Medal", postNominal: "CnM" },
    { name: "the Jubilee Medal", postNominal: "JM" },
    { name: "the Lifesaving Medal", postNominal: "LfM" },
    { name: "the Campaign Star", postNominal: "CSt" },
  ],
  t1: [
    { name: "the Long Service Medal of the Electoral Court", postNominal: "LSM" },
    { name: "the Wittgenau Cross, Second Class", postNominal: "WC2" },
    { name: "the Osterfeld Merit Cross", postNominal: "OMC" },
    { name: "the Electoral Household Medal", postNominal: "EHM" },
    { name: "the Two Wexcombes Commemorative Medal", postNominal: "TWC" },
    { name: "the Long Winter Medal", postNominal: "LWM" },
    { name: "the Bridge Defence Medal", postNominal: "BDM" },
    { name: "the Beacon Service Star", postNominal: "BSS" },
    { name: "the Harvest Medal", postNominal: "HvM" },
    { name: "the River Crossing Cross", postNominal: "RCC" },
    { name: "the Garrison Medal", postNominal: "GRM" },
    { name: "the Frontier Survey Medal, with Compass Rose", postNominal: "FSMc" },
  ],
  t2: [
    { name: "the Medal of the Damp, Second Class", postNominal: "MD2" },
    { name: "the Household Order of the Butter Dish, Third Class", postNominal: "BD3" },
    { name: "the Tidy Shed Rosette", postNominal: "TSR" },
    { name: "the Perfect Attendance Medal", postNominal: "PAM" },
    { name: "the Bake Sale Cross", postNominal: "BSC" },
    { name: "the Car Park Star", postNominal: "CPkS" },
    { name: "the Tombola Cross", postNominal: "TBC" },
    { name: "the Sponsored Walk Medal", postNominal: "SWM" },
    { name: "the Best Kept Verge Medal", postNominal: "BKV" },
    { name: "the Returned Casserole Dish Medal", postNominal: "RCD" },
    { name: "the Punctuality Star, Second Class", postNominal: "PS2" },
    { name: "the Medal of the Raffle (Unclaimed)", postNominal: "MRU" },
  ],
};

export const ACADEMIC: { t0: readonly DecorationRow[]; t1: readonly DecorationRow[]; t2: readonly DecorationRow[] } = {
  t0: [
    { name: "Fellow of the Royal Society of Wittgenau", postNominal: "FRSW" },
    { name: "Fellow of the Society of Antiquaries of Wexcombe", postNominal: "FSAW" },
    { name: "Fellow of the Imperial Academy of Osterfeld", postNominal: "FIAO" },
    { name: "Member of the Antiquarian Society of Hohenfelsen", postNominal: "MAntS" },
    { name: "Fellow of the College of Heralds of Wexcombe", postNominal: "FCHW" },
    { name: "Corresponding Fellow of the Society of the Marches", postNominal: "CFSM" },
    { name: "Doctor of Laws of the University of the Two Wexcombes", postNominal: "LLD (Wexc)" },
    { name: "Reader in Heraldry of the College of Wexcombe", postNominal: "RHW" },
  ],
  t1: [
    { name: "Corresponding Member of the Academy of the Two Wexcombes", postNominal: "CMAW" },
    { name: "Honorary Doctor of the University of Osterfeld", postNominal: "DrOst (hc)" },
    { name: "Visiting Reader in Precedence Studies", postNominal: "VRPS" },
    { name: "Licentiate of the Academy of Falconry", postNominal: "LAF" },
    { name: "External Examiner in Blazonry", postNominal: "EEB" },
    { name: "Fellow of the Institute of Genealogical Conjecture", postNominal: "FIGC" },
    { name: "Honorary Archivist of the Electoral Court", postNominal: "HAEC" },
    { name: "Doctor of Letters of the University of Osterfeld, by Post", postNominal: "DLitt (Post)" },
  ],
  t2: [
    { name: "Fellow of the Royal Society of Biscuitry", postNominal: "FRSB" },
    { name: "Reader Emeritus in Cupboard Studies", postNominal: "RECS" },
    { name: "Fellow of the Royal Society of Doilies", postNominal: "FRSD" },
    { name: "Visiting Professor of Cupboard Studies", postNominal: "VPCS" },
    { name: "Bachelor of the Airing-Cupboard", postNominal: "BAC" },
    { name: "Diploma in Advanced Queueing", postNominal: "Dip.Q." },
    { name: "Fellow of the Institute of Thermostat Management", postNominal: "FITM" },
    { name: "Master of Biscuit Philosophy", postNominal: "MBPhil" },
  ],
};

/* ------------------------------------------------------------------ */
/* Formulas and protective formulas                                    */
/* ------------------------------------------------------------------ */

export interface FormulaRow {
  en: string;
  /** Latin form used when antiquity runs high. */
  la?: string;
}

export const FORMULAS: { t0: readonly FormulaRow[]; t1: readonly FormulaRow[]; t2: readonly FormulaRow[] } = {
  t0: [
    { en: "by the Grace of God", la: "Dei Gratia" },
    { en: "by Right of Conquest" },
    { en: "by Right of Birth" },
    { en: "by Lawful Succession" },
    { en: "by Ancient Custom", la: "More Maiorum" },
    { en: "by the Grace of God and Right of Birth" },
  ],
  t1: [
    { en: "by the Grace of God and the Will of the Electors" },
    { en: "by the Grace of God and the Consent of the Estates" },
    { en: "by the Grace of God and the Will of the Nation" },
    { en: "by the Grace of God and the Acclamation of the Host" },
    { en: "by the Grace of God and the Assent of the Burghers" },
    { en: "by the Grace of God and the Verdict of the Twelve Elders" },
    { en: "by the Grace of God and the Treaty of the Three Rivers" },
    { en: "by the Grace of God and the Custom of the Valley" },
    { en: "by the Grace of God and the Findings of the Herald" },
    { en: "by the Grace of God and the Second Reading" },
  ],
  t2: [
    { en: "by the Grace of God and the Parish Council (disputed)" },
    { en: "by the Grace of God and a Narrow Vote" },
    { en: "by Sufferance of the Tenants" },
    { en: "by the Grace of God and the Residents' Association (minuted)" },
    { en: "by the Grace of God and the Rota" },
    { en: "by the Grace of God and the Sub-Committee (quorate)" },
    { en: "by the Grace of God and a Show of Hands" },
    { en: "by the Grace of God and the Minutes of the Last Meeting (approved)" },
    { en: "by the Grace of God and the Raffle" },
    { en: "by the Grace of God and the Casting Vote" },
    { en: "by the Grace of God and the Amended Agenda" },
    { en: "by the Grace of God and the Postal Ballot" },
    { en: "by Standing Order" },
    { en: "by the Kind Permission of the Management" },
    { en: "by the Grace of God and the Deposit (non-refundable)" },
    { en: "by the Grace of God and the Book of Signatures (two witnesses)" },
  ],
};

export const PROTECTIVE = {
  t0: [
    "Defender of the Faith", "Protector of the Realm",
    "Guardian of the Marches", "Keeper of the Two Roads",
    "Guardian of the Passes", "Warden of the Northern Gate",
    "Shield of the Marches", "Protector of the Roads and Bridges",
    "Keeper of the Fords", "Guardian of the Harvest",
    "Warden of the Beacons", "Protector of Pilgrims and Merchants",
    "Guardian of the Old Walls", "Keeper of the Peace of the Fairs",
    "Protector of the Widowed and the Orphaned",
    "Warden of the Sea Approaches", "Shield of the Uplands",
    "Guardian of the Granaries", "Keeper of the Ancient Liberties",
  ],
  t1: [
    "Advocate of the Abbey of Wittgenau", "Protector of the Lesser Forests",
    "Warden of the Coasts", "Advocate of the Abbey of Netherleigh",
    "Protector of the Nine Bridges",
    "Guarantor of the Old Weights and Measures",
    "Warden of the Winter Grain", "Keeper of the Common Seal",
    "Protector of the Second Harbour", "Advocate of the Priory of Osterfeld",
    "Guardian of the Disputed Meadow", "Warden of the Middle Marches",
    "Keeper of the Treaty Stone", "Protector of the Salt Pans",
    "Guarantor of the Ferry Rights", "Shield of the Lower Valleys",
    "Guardian of the Beacon Hills", "Warden of the Old Toll Gates",
    "Protector of the Mill Streams", "Advocate of the Charterhouse of Wexley",
    "Keeper of the Boundary Oaks", "Guarantor of the Market Peace",
    "Warden of the Pilgrim Roads", "Protector of the High Pastures",
  ],
  t2: [
    "Defender of the Biscuit", "Protector of the Lesser Cupboard (Contents)",
    "Guarantor of the Thermostat", "Keeper of the Spare Keys",
    "Defender of the Doormat", "Upholder of the Banister",
    "Defender of the Serviettes", "Protector of the Spare Room (Bookings)",
    "Guarantor of the Deposit", "Upholder of the Standing Orders",
    "Defender of the Last Biscuit (Contested)",
    "Shield of the Draining Board",
    "Guardian of the Guest Towels (Display Only)",
    "Warden of the Thermostat (Winter Setting)",
    "Protector of the Doilies (Sunday)", "Advocate of the Potting Shed",
    "Keeper of the Peace of the Landing", "Defender of the Quorum",
    "Guarantor of the Tea Round", "Upholder of the Bin Rota",
    "Protector of the Good China (Occasions Only)",
    "Defender of the Window Seat", "Guardian of the Remote Control",
    "Shield of the Picnic Hamper", "Guarantor of the Raffle (Prizes Vary)",
    "Protector of the Cloakroom Tickets", "Defender of the Agenda",
    "Upholder of the Minute Book", "Guardian of the Filing Cabinet",
    "Keeper of the Faith of the Sub-Committee",
    "Protector of the Airing-Cupboard (Shelf Two)",
  ],
} as const;

/* ------------------------------------------------------------------ */
/* Mottoes                                                             */
/* ------------------------------------------------------------------ */

export interface MottoRow {
  text: string;
  language: "la" | "fr" | "en" | "mixed";
}

export const MOTTOES: { t0: readonly MottoRow[]; t1: readonly MottoRow[]; t2: readonly MottoRow[] } = {
  // Invented but grammatical.
  t0: [
    { text: "Fide et Fortitudine", language: "la" },
    { text: "Virtute Non Verbis", language: "la" },
    { text: "Constantia et Labore", language: "la" },
    { text: "Sub Umbra Quiescens", language: "la" },
    { text: "Droit et Loyal", language: "fr" },
    { text: "Lumen in Tenebris", language: "la" },
    { text: "Semper Vigilans", language: "la" },
    { text: "Fortis in Arduis", language: "la" },
    { text: "Nec Temere Nec Timide", language: "la" },
    { text: "Per Varios Casus", language: "la" },
    { text: "Lente Sed Certe", language: "la" },
    { text: "In Umbra Floresco", language: "la" },
    { text: "Ex Silentio Robur", language: "la" },
    { text: "Fide Sed Cui Vide", language: "la" },
    { text: "Aquila Non Capit Muscas", language: "la" },
    { text: "Sine Macula", language: "la" },
    { text: "Montani Semper Liberi", language: "la" },
    { text: "Vigilo et Spero", language: "la" },
    { text: "Nec Cede Malis", language: "la" },
    { text: "Toujours Fidèle", language: "fr" },
    { text: "Sans Changer", language: "fr" },
    { text: "Ferme en Foy", language: "fr" },
    { text: "Post Nubila Phoebus", language: "la" },
    { text: "Aut Viam Inveniam", language: "la" },
    { text: "Stella Duce", language: "la" },
    { text: "Radix Firma", language: "la" },
  ],
  // Correct Latin, suspicious sentiments.
  t1: [
    { text: "Festina Lentissime", language: "la" },
    { text: "Semper Aliquantulum", language: "la" },
    { text: "Dum Spiro, Dormio", language: "la" },
    { text: "Post Nubila, Merenda", language: "la" },
    { text: "Cras Incipiam", language: "la" },
    { text: "Satis Superque", language: "la" },
    { text: "Vix Sed Tamen", language: "la" },
    { text: "Prandium Primum", language: "la" },
    { text: "Post Meridiem Nihil Novi", language: "la" },
    { text: "Dormio Ergo Sum", language: "la" },
    { text: "Melius Cras", language: "la" },
    { text: "Paulatim Sed Nunquam", language: "la" },
    { text: "Sedendo Vinco", language: "la" },
    { text: "Otium Cum Dignitate", language: "la" },
    { text: "Festinare Nocet", language: "la" },
    { text: "In Dubio, Merenda", language: "la" },
    { text: "Aliquando Surgam", language: "la" },
    { text: "Nemo Me Impune Invitat", language: "la" },
    { text: "Video Sed Taceo", language: "la" },
    { text: "Nolo Sed Debeo", language: "la" },
    { text: "Fere Semper Paratus", language: "la" },
    { text: "Plus Minusve", language: "la" },
    { text: "Adhuc Considero", language: "la" },
    { text: "Mox, Fortasse", language: "la" },
  ],
  // The joke must be visible to a non-Latinist: an English word in a
  // Latin frame.
  t2: [
    { text: "Semper Damp", language: "mixed" },
    { text: "Nihil Sine Receipt", language: "mixed" },
    { text: "Post Prandium Nihil", language: "la" },
    { text: "In Cupboard Veritas", language: "mixed" },
    { text: "Per Biscuit ad Astra", language: "mixed" },
    { text: "Non Sine Teapot", language: "mixed" },
    { text: "Honi Soit Qui Mal y Biscuit", language: "mixed" },
    { text: "Semper Tidy", language: "mixed" },
    { text: "Nihil Sine Kettle", language: "mixed" },
    { text: "Sic Transit Gravy", language: "mixed" },
    { text: "E Pluribus Biscuit", language: "mixed" },
    { text: "Carpe Thermos", language: "mixed" },
    { text: "Veni, Vidi, Tidied", language: "mixed" },
    { text: "Quod Erat Laundrandum", language: "mixed" },
    { text: "Cogito Ergo Cupboard", language: "mixed" },
    { text: "Nunc Aut Teatime", language: "mixed" },
    { text: "Ad Astra Per Stairwell", language: "mixed" },
    { text: "In Loco Pantry", language: "mixed" },
    { text: "Pax et Marmalade", language: "mixed" },
    { text: "Excelsior (Within Reason)", language: "mixed" },
    { text: "Sursum Kettle", language: "mixed" },
    { text: "Sans Peur et Sans Serviette", language: "mixed" },
    { text: "Toujours Tidy", language: "mixed" },
    { text: "Après Moi, le Mop", language: "mixed" },
    { text: "Dum Vivimus, Dustimus", language: "mixed" },
    { text: "Tempus Fugit, Kettle Boilit", language: "mixed" },
    { text: "Ars Longa, Queue Longa", language: "mixed" },
    { text: "Amor Vincit Doormat", language: "mixed" },
    { text: "Ex Cupboard Lux", language: "mixed" },
    { text: "Per Doily ad Gloriam", language: "mixed" },
    { text: "Nil Desperandum, Nil Refundandum", language: "mixed" },
    { text: "Memento Mopi", language: "mixed" },
    { text: "Habeas Biscuit", language: "mixed" },
    { text: "Caveat Borrower", language: "mixed" },
    { text: "Status Quo Ante Teatime", language: "mixed" },
    { text: "De Minimis Non Curat Larder", language: "mixed" },
    { text: "Ipso Facto Tidy", language: "mixed" },
  ],
};

/* ------------------------------------------------------------------ */
/* Title statuses                                                      */
/* ------------------------------------------------------------------ */

import type { TitleStatus } from "../types.js";

/** Non-held statuses with weights, drawn as pretension climbs. */
export const PRETENDER_STATUSES: readonly (readonly [TitleStatus, number])[] = [
  ["titular", 3], ["claimed", 3], ["in-pretence", 2], ["disputed", 2],
  ["de-jure", 2], ["in-exile", 1], ["dormant", 1], ["vacant", 1],
];
